import Foundation
import FirebaseAuth
import FirebaseFirestore
import FirebaseStorage
import CryptoKit
// At top-level in CloudBackupService.swift
import Combine

public enum BackupState: String {
    case idle, scanning, preparing, uploading, finishing, error, restoring
}

public struct BackupProgress {
    public var state: BackupState
    public var total: Int
    public var done: Int
    public var currentName: String?   // optional display (clipId / filename)
}

public struct BackupSummary: Identifiable {
    public let id: String          // backupId
    public let name: String
    public let status: String
    public let createdAt: Date
    public let updatedAt: Date?
    public let deviceName: String?
    public let clipCount: Int

    public var displayDate: Date {
        updatedAt ?? createdAt
    }

    public var displayName: String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return Self.autoGeneratedName(for: displayDate) }
        if trimmed.hasPrefix("Backup ") {
            return Self.autoGeneratedName(for: displayDate)
        }
        return trimmed
    }

    private static func autoGeneratedName(for date: Date) -> String {
        "Backup \(date.formatted(date: .abbreviated, time: .shortened))"
    }
}

// Throttle parallel tasks
actor Gate {
    private var permits: Int
    init(_ n: Int) { permits = n }
    func acquire() async {
        while permits == 0 { await Task.yield() }
        permits -= 1
    }
    func release() async { permits += 1 }
}

actor Counter {
    private var value = 0
    func inc() -> Int { value += 1; return value }
}

actor FirestoreMetadataWriter {
    private let db = Firestore.firestore()
    private let col: CollectionReference
    private var pending: [[String: Any]] = []
    private var pendingIds: [String] = []
    private var flushScheduled = false
    private let batchSize = 200
    private let debounceMs: UInt64 = 400

    init(collection: CollectionReference) {
        self.col = collection
    }

    func enqueue(id: String, doc: [String: Any]) {
        pending.append(doc)
        pendingIds.append(id)
        if pending.count >= batchSize {
            Task { await flushNow() }
        } else if !flushScheduled {
            flushScheduled = true
            Task {
                try? await Task.sleep(nanoseconds: debounceMs * 1_000_000)
                await flushNow()
            }
        }
    }

    private func shouldRetry(_ err: Error) -> Bool {
        let ns = err as NSError
        // App Check / permission / transient
        return ns.domain == FirestoreErrorDomain
            || ns.code == 7 /* PERMISSION_DENIED */
            || ns.code == 14 /* UNAVAILABLE */
            || ns.code == 4  /* DEADLINE_EXCEEDED */
    }

    private func backoff(_ attempt: Int) async {
        let baseMs = 250
        let capMs  = 4000
        let delay  = min(capMs, baseMs << attempt)
        try? await Task.sleep(nanoseconds: UInt64(delay) * 1_000_000)
    }

    private func takeBatch() -> (ids: [String], docs: [[String: Any]]) {
        let n = min(batchSize, pending.count)
        let docs = Array(pending.prefix(n))
        let ids  = Array(pendingIds.prefix(n))
        pending.removeFirst(n)
        pendingIds.removeFirst(n)
        return (ids, docs)
    }

    private func putBack(ids: [String], docs: [[String: Any]]) {
        pending = docs + pending
        pendingIds = ids + pendingIds
    }

    private func hasWork() -> Bool { !pending.isEmpty }

    func flushNow() async {
        flushScheduled = false
        guard hasWork() else { return }

        var attempt = 0
        while hasWork() {
            let (ids, docs) = takeBatch()
            do {
                let batch = db.batch()
                for (i, d) in docs.enumerated() {
                    let id = ids[i]
                    let docRef = col.document(id)
                    batch.setData(d, forDocument: docRef, merge: true)
                }
                try await batch.commit()
            } catch {
                // Retry on AppCheck/permission/transient
                if shouldRetry(error) && attempt < 5 {
                    attempt += 1
                    await backoff(attempt)
                    // Put the batch back and try again
                    putBack(ids: ids, docs: docs)
                } else {
                    print("❌ Firestore batch commit failed: \(error.localizedDescription)")
                }
            }
        }
    }
}




struct HashKey: Hashable, Sendable {
    let path: String
    let size: Int64
    let mtime: TimeInterval
}

private actor BackupHashCache {
    private var values: [HashKey: String] = [:]

    func value(for key: HashKey) -> String? {
        values[key]
    }

    func store(_ hash: String, for key: HashKey) {
        values[key] = hash
    }
}

/// Single source of truth for backup/sync logic.
@MainActor
final class CloudBackupService: ObservableObject {
    static let shared = CloudBackupService()

    // Session/auth guard
    private var isSignedIn: Bool {
        guard let u = Auth.auth().currentUser, !u.isAnonymous else { return false }
        // If backup is OFF, uid may be nil; attach it lazily so restore can proceed.
        if self.uid == nil { self.uid = u.uid }
        return true
    }


    private var metadataWriter: FirestoreMetadataWriter?

    private let db = Firestore.firestore()
    private let storage = Storage.storage()
    private let worker = AsyncSerialWorker()

    // Add near top of CloudBackupService
    private let defaults = UserDefaults.standard
    private let activeIdKey = "cloudBackup.activeId"

    private let maxParallelUploads = 2  // tweak: 2–4 is a good range
    private let maxParallelHashes  = 2

    // Cancellation & task tracking
    private var isShuttingDown = false
    private var uploadTasks = [StorageUploadTask]()


    // Coalesce multiple triggers of the initial scan/upload into a single run.
    private var initialBackupTask: Task<Void, Never>?

    // Cancel any in-flight initial full backup and clear the gate.
    private func cancelInitialBackupIfRunning() {
        if let t = initialBackupTask {
            t.cancel()
            initialBackupTask = nil
        }
    }

    /// Start the initial full backup. If `forceRestart` is true, cancel any stale/in-flight task first.
    private func startInitialBackup(forceRestart: Bool = false) {
        if forceRestart { cancelInitialBackupIfRunning() }
        else if initialBackupTask != nil {
            print("ℹ️ initialFullBackup already running; skipping trigger")
            return
        }

        initialBackupTask = Task { [weak self] in
            guard let self else { return }
            await self.initialFullBackup()
            await MainActor.run { self.initialBackupTask = nil }
        }
    }





    private actor AsyncSerialWorker {
        func run<T>(_ op: @escaping () async throws -> T) async throws -> T {
            try await op()
        }
    }

    @Published private(set) var uid: String?
    private nonisolated let hashCache = BackupHashCache()


    // A provider your app registers so we can enumerate current local clips.
    // Keep it simple: one shot enumeration when initial backup runs.
    private var enumerator: (@MainActor () -> [UnhashedLocalClip])?

    private let progressSubject = PassthroughSubject<BackupProgress, Never>()
    public var progressPublisher: AnyPublisher<BackupProgress, Never> { progressSubject.eraseToAnyPublisher() }

    private func publish(_ p: BackupProgress) {
        // ensure UI gets updates on main
        DispatchQueue.main.async { self.progressSubject.send(p) }
    }

    // MARK: - Restore glue (provided by app)
    public typealias LocalProbe = (_ id: String, _ ext: String) -> URL?            // return existing file URL if present
    public typealias LocalCommit = (
        _ id: String, _ tempURL: URL, _ createdAt: Date, _ journalId: String?, _ ext: String) throws -> Void

    private var restoreProbe: LocalProbe?
    private var restoreCommit: LocalCommit?

    public func registerRestoreHandlers(probe: @escaping LocalProbe, commit: @escaping LocalCommit) {
        self.restoreProbe = probe
        self.restoreCommit = commit
    }

    // MARK: - Journal backup/restore plumbing
    public struct BackupJournal: Codable, Hashable {
        public let id: String   // UUID string
        public let name: String
        public let createdAt: Date
        public let type: String
        public let sortIndex: Int
    }

    struct RestoreJournalReference: Hashable {
        let id: String
        let name: String?
        let createdAt: Date?
        let type: String?
        let sortIndex: Int?
    }

    private var journalSnapshotProvider: (@MainActor () -> [BackupJournal])?
    private var journalRebuilder: (([BackupJournal]) async -> Void)?

    public func registerJournalHandlers(snapshot: @escaping @MainActor () -> [BackupJournal],
                                        rebuild: @escaping ([BackupJournal]) async -> Void) {
        self.journalSnapshotProvider = snapshot
        self.journalRebuilder = rebuild
        if self.activeBackupId != nil {
            Task { await self.syncActiveJournalSnapshotIfNeeded() }
        }
    }

    private func journalsCollection(_ backupId: String) throws -> CollectionReference {
        try backupDoc(backupId).collection("journals")
    }

    private func journalDocumentData(for journal: BackupJournal) -> [String: Any] {
        [
            "name": journal.name,
            "createdAt": Timestamp(date: journal.createdAt),
            "type": journal.type,
            "sortIndex": journal.sortIndex
        ]
    }

    private func decodeJournal(documentID: String,
                               data: [String: Any],
                               fallbackSortIndex: Int) -> BackupJournal {
        BackupJournal(
            id: documentID,
            name: Self.normalizedJournalName(data["name"] as? String, fallback: "Restored Journal"),
            createdAt: (data["createdAt"] as? Timestamp)?.dateValue() ?? Date(timeIntervalSince1970: 0),
            type: Self.normalizedJournalType(data["type"] as? String),
            sortIndex: Self.intValue(data["sortIndex"]) ?? fallbackSortIndex
        )
    }

    private static func normalizedJournalName(_ raw: String?, fallback: String) -> String {
        let trimmed = raw?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return trimmed.isEmpty ? fallback : trimmed
    }

    private static func normalizedJournalType(_ raw: String?) -> String {
        let trimmed = raw?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return trimmed.isEmpty ? "dailyJournal" : trimmed
    }

    private static func int64Value(_ raw: Any?) -> Int64? {
        switch raw {
        case let value as Int64:
            return value
        case let value as Int:
            return Int64(value)
        case let value as NSNumber:
            return value.int64Value
        default:
            return nil
        }
    }

    private static func intValue(_ raw: Any?) -> Int? {
        switch raw {
        case let value as Int:
            return value
        case let value as Int64:
            return Int(value)
        case let value as NSNumber:
            return value.intValue
        default:
            return nil
        }
    }

    private func touchBackup(_ backupId: String) async {
        do {
            try await backupDoc(backupId).setData([
                "updatedAt": FieldValue.serverTimestamp()
            ], merge: true)
        } catch {
            print("⚠️ Could not update backup timestamp for \(backupId): \(error.localizedDescription)")
        }
    }

    func syncActiveJournalSnapshotIfNeeded() async {
        guard isSignedIn, let backupId = activeBackupId, let snapshot = journalSnapshotProvider else {
            return
        }

        do {
            let journals = snapshot()
            let jcol = try journalsCollection(backupId)
            let existing = try await jcol.getDocuments()
            let existingIDs = Set(existing.documents.map(\.documentID))
            let currentIDs = Set(journals.map(\.id))

            if !journals.isEmpty || !existingIDs.isEmpty {
                let batch = db.batch()
                for journal in journals {
                    batch.setData(
                        journalDocumentData(for: journal),
                        forDocument: jcol.document(journal.id),
                        merge: true
                    )
                }
                for staleID in existingIDs.subtracting(currentIDs) {
                    batch.deleteDocument(jcol.document(staleID))
                }
                try await batch.commit()
            }

            await touchBackup(backupId)
        } catch {
            print("⚠️ Failed to sync journals for backup \(backupId): \(error.localizedDescription)")
        }
    }

    static func mergeBackupJournals(remoteJournals: [BackupJournal],
                                    clipReferences: [RestoreJournalReference],
                                    fallbackJournals: [BackupJournal]) -> [BackupJournal] {
        var merged = Dictionary(uniqueKeysWithValues: remoteJournals.map { ($0.id, $0) })
        let fallbackByID = Dictionary(uniqueKeysWithValues: fallbackJournals.map { ($0.id, $0) })
        let maxKnownSortIndex = (remoteJournals.map(\.sortIndex) + fallbackJournals.map(\.sortIndex)).max() ?? -1
        var nextSortIndex = maxKnownSortIndex
        var placeholderOrdinal = 1

        var referencesByID: [String: RestoreJournalReference] = [:]
        for ref in clipReferences {
            if let existing = referencesByID[ref.id] {
                referencesByID[ref.id] = RestoreJournalReference(
                    id: ref.id,
                    name: existing.name ?? ref.name,
                    createdAt: existing.createdAt ?? ref.createdAt,
                    type: existing.type ?? ref.type,
                    sortIndex: existing.sortIndex ?? ref.sortIndex
                )
            } else {
                referencesByID[ref.id] = ref
            }
        }

        for ref in referencesByID.values.sorted(by: { $0.id < $1.id }) {
            guard merged[ref.id] == nil else { continue }

            if let fallback = fallbackByID[ref.id] {
                merged[ref.id] = BackupJournal(
                    id: fallback.id,
                    name: Self.normalizedJournalName(ref.name, fallback: fallback.name),
                    createdAt: ref.createdAt ?? fallback.createdAt,
                    type: ref.type.map { Self.normalizedJournalType($0) } ?? fallback.type,
                    sortIndex: ref.sortIndex ?? fallback.sortIndex
                )
                continue
            }

            nextSortIndex += 1
            let placeholderName = Self.normalizedJournalName(
                ref.name,
                fallback: "Restored Journal \(placeholderOrdinal)"
            )
            placeholderOrdinal += 1

            merged[ref.id] = BackupJournal(
                id: ref.id,
                name: placeholderName,
                createdAt: ref.createdAt ?? Date(timeIntervalSince1970: 0),
                type: ref.type.map { Self.normalizedJournalType($0) } ?? "dailyJournal",
                sortIndex: ref.sortIndex ?? nextSortIndex
            )
        }

        return merged.values.sorted {
            if $0.sortIndex != $1.sortIndex { return $0.sortIndex < $1.sortIndex }
            if $0.createdAt != $1.createdAt { return $0.createdAt < $1.createdAt }
            return $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending
        }
    }



    // Lightweight type from your app before hashing
    struct UnhashedLocalClip {
        let id: String
        let fileURL: URL
        let createdAt: Date
        let journalId: String?
        let ext: String
    }

    public func registerEnumerator(_ block: @escaping @MainActor () -> [UnhashedLocalClip]) {
        self.enumerator = block
    }

    @Published private(set) var activeBackupId: String?   // NEW

    private func backupDoc(_ backupId: String) throws -> DocumentReference {
        guard let uid else { throw BackupError.missingUser }
        return db.collection("users").document(uid)
                 .collection("backups").document(backupId)
    }

    private func clipsCollection(_ backupId: String) throws -> CollectionReference {
        try backupDoc(backupId).collection("clips")
    }

    private func clipsBucket(_ backupId: String) throws -> StorageReference {
        guard let uid else { throw BackupError.missingUser }
        return storage.reference(withPath: "users/\(uid)/backups/\(backupId)/clips")
    }

    public func listBackups(for uid: String) async throws -> [BackupSummary] {
        let col = db.collection("users").document(uid).collection("backups")
        let snap = try await col.getDocuments(source: .server)

        var results: [BackupSummary] = []
        results.reserveCapacity(snap.documents.count)

        for d in snap.documents {
            let data = d.data()
            let name = (data["name"] as? String) ?? d.documentID
            let status = (data["status"] as? String) ?? "unknown"
            let deviceName = data["deviceName"] as? String
            let createdAt: Date = (data["createdAt"] as? Timestamp)?.dateValue() ?? Date(timeIntervalSince1970: 0)
            let updatedAt: Date? = (data["updatedAt"] as? Timestamp)?.dateValue()

            let clipsQuery = d.reference.collection("clips").whereField("deleted", isEqualTo: false)
            let agg = try await clipsQuery.count.getAggregation(source: .server)
            let clipCount = Int(truncating: agg.count)

            results.append(BackupSummary(
                id: d.documentID,
                name: name,
                status: status,
                createdAt: createdAt,
                updatedAt: updatedAt,
                deviceName: deviceName,
                clipCount: clipCount
            ))
        }

        results.sort { lhs, rhs in
            lhs.displayDate > rhs.displayDate
        }
        return results
    }


    public enum RestoreMode { case missingOnly, overwriteAll }

    public func restoreBackup(backupId: String, mode: RestoreMode = .missingOnly) async {
        // In case backup was OFF and uid was cleared, reattach from Firebase now.
        if self.uid == nil, let u = Auth.auth().currentUser, !u.isAnonymous { self.uid = u.uid }

        guard isSignedIn, let probe = restoreProbe, let commit = restoreCommit else {
            print("ℹ️ restoreBackup: blocked (not signed in or handlers missing)")
            publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
            return
        }

        publish(.init(state: .restoring, total: 0, done: 0, currentName: nil))

        do {
            // 1) Fetch remote clip docs in one round-trip
            let coll = try clipsCollection(backupId)
            let snap = try await coll.getDocuments()
            struct Remote: Hashable {
                let id: String
                let ext: String
                let sha: String
                let bytes: Int64
                let createdAt: Date
                let journalId: String?
                let journalName: String?
                let journalCreatedAt: Date?
                let journalType: String?
                let journalSortIndex: Int?
            }
            var remote: [Remote] = []
            remote.reserveCapacity(snap.documents.count)

            for d in snap.documents {
                let data = d.data()
                guard
                    let sha = data["sha256"] as? String,
                    let bytes = Self.int64Value(data["bytes"]),
                    let ext = data["ext"] as? String,
                    let created = (data["createdAt"] as? Timestamp)?.dateValue()
                else { continue }
                let id = d.documentID
                let jid = data["journalId"] as? String
                let journalName = data["journalName"] as? String
                let journalCreatedAt = (data["journalCreatedAt"] as? Timestamp)?.dateValue()
                let journalType = data["journalType"] as? String
                let journalSortIndex = Self.intValue(data["journalSortIndex"])
                let deleted = (data["deleted"] as? Bool) ?? false
                if !deleted {
                    remote.append(.init(
                        id: id,
                        ext: ext,
                        sha: sha,
                        bytes: bytes,
                        createdAt: created,
                        journalId: jid,
                        journalName: journalName,
                        journalCreatedAt: journalCreatedAt,
                        journalType: journalType,
                        journalSortIndex: journalSortIndex
                    ))
                }
            }

            // 2) Rebuild journals before restoring any clips.
            if mode == .overwriteAll, let rebuild = journalRebuilder {
                let jcol = try journalsCollection(backupId)
                let jsnap = try await jcol.getDocuments()
                var remoteJournals: [BackupJournal] = []
                remoteJournals.reserveCapacity(jsnap.documents.count)
                for (index, d) in jsnap.documents.enumerated() {
                    remoteJournals.append(
                        decodeJournal(
                            documentID: d.documentID,
                            data: d.data(),
                            fallbackSortIndex: index
                        )
                    )
                }

                let clipJournalRefs = remote.compactMap { clip -> RestoreJournalReference? in
                    guard let journalId = clip.journalId else { return nil }
                    return RestoreJournalReference(
                        id: journalId,
                        name: clip.journalName,
                        createdAt: clip.journalCreatedAt,
                        type: clip.journalType,
                        sortIndex: clip.journalSortIndex
                    )
                }

                let localFallbacks = journalSnapshotProvider?() ?? []
                let journals = Self.mergeBackupJournals(
                    remoteJournals: remoteJournals,
                    clipReferences: clipJournalRefs,
                    fallbackJournals: localFallbacks
                )

                if remoteJournals.count < Set(clipJournalRefs.map(\.id)).count {
                    print("⚠️ Restore recovered missing journal metadata from clip references/local fallback.")
                }

                await rebuild(journals)
            }

            // 3) Decide which need restore
            var toRestore: [Remote] = []
            toRestore.reserveCapacity(remote.count)
            for r in remote {
                if mode == .overwriteAll {
                    toRestore.append(r)
                    continue
                }
                // missingOnly: if local exists and hash matches, ensure metadata, then skip download
                if let url = probe(r.id, r.ext),
                   let attrs = try? FileManager.default.attributesOfItem(atPath: url.path),
                   let size = (attrs[.size] as? NSNumber)?.int64Value,
                   let localSha = try? sha256(forFileAt: url),
                   size == r.bytes, localSha == r.sha {
                    do {
                        try commit(r.id, url, r.createdAt, r.journalId, r.ext) // <-- re-create DB record
                    } catch {
                        print("⚠️ restore ensure-meta failed for \(r.id): \(error.localizedDescription)")
                        // Optional: fall back to download if commit requires temp files
                        // toRestore.append(r)
                    }
                    continue
                }
                toRestore.append(r)
            }

            // 4) Download in parallel (capped)
            let total = toRestore.count
            publish(.init(state: .restoring, total: total, done: 0, currentName: nil))
            guard total > 0 else {
                publish(.init(state: .finishing, total: 0, done: 0, currentName: nil))
                publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
                print("✅ Restore: nothing to do; local library already matches backup.")
                return
            }

            let gate = Gate(maxParallelUploads)    // reuse your Gate (3–4 is fine for downloads too)
            let counter = Counter()
            let bucket = try self.clipsBucket(backupId)  // Storage folder ref

            await withTaskGroup(of: Void.self) { group in
                for r in toRestore {
                    group.addTask {
                        await gate.acquire()
                        defer { Task { await gate.release() } }

                        let ref = bucket.child("\(r.id).\(r.ext)")
                        // download to a temp file
                        let tmp = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("\(r.id).\(r.ext)")
                        do {
                            try? FileManager.default.removeItem(at: tmp)
                            try await self.download(to: tmp, from: ref)
                            // verify
                            let sha = try sha256(forFileAt: tmp)
                            let attrs = try FileManager.default.attributesOfItem(atPath: tmp.path)
                            let bytes = (attrs[.size] as? NSNumber)?.int64Value ?? -1
                            guard sha == r.sha, bytes == r.bytes else {
                                throw NSError(domain: "Restore", code: -1, userInfo: [NSLocalizedDescriptionKey: "Hash/size mismatch for \(r.id)"])
                            }
                            // hand back to app (moves to library + DB)
                            try commit(r.id, tmp, r.createdAt, r.journalId, r.ext)
                        } catch {
                            print("❌ Restore failed for \(r.id): \(error.localizedDescription)")
                        }

                        let done = await counter.inc()
                        await MainActor.run {
                            self.publish(.init(state: .restoring, total: total, done: done, currentName: r.id))
                        }
                    }
                }
                await group.waitForAll()
            }

            publish(.init(state: .finishing, total: 0, done: 0, currentName: nil))
            publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
            print("✅ Restore complete (\(toRestore.count) items)")
        } catch {
            print("❌ restoreBackup error:", error.localizedDescription)
            publish(.init(state: .error, total: 0, done: 0, currentName: nil))
        }
    }


    private func download(to url: URL, from ref: StorageReference) async throws {
        try await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, Error>) in
            let task = ref.write(toFile: url) { _, error in
                if let error { cont.resume(throwing: error) } else { cont.resume(returning: ()) }
            }
            // (optional) observe
            task.observe(.failure) { snap in
                if let e = snap.error { print("❌ download failure \(ref.fullPath): \(e.localizedDescription)") }
            }
        }
    }




    // MARK: - Enable/Disable
    // Expose the gate to UI (avoids calling initialFullBackup() directly)
    public func performInitialBackupGate() {
        startInitialBackup(forceRestart: false)
    }


    func enableBackup(for uid: String) async throws {
        self.uid = uid

        // Restore last active session if present and still active
        if let savedId = defaults.string(forKey: activeIdKey) {
            do {
                let doc = try await backupDoc(savedId).getDocument()
                if (doc.data()?["status"] as? String) == "active" {
                    self.activeBackupId = savedId
                    // ⬇️ initialize metadata writer for incremental events
                    let col = try self.clipsCollection(savedId)
                    self.metadataWriter = FirestoreMetadataWriter(collection: col)
                    await self.syncActiveJournalSnapshotIfNeeded()

                    // ⬇️ auto-resume the initial full upload of any remaining clips
                    publish(.init(state: .scanning, total: 0, done: 0, currentName: nil))
                    startInitialBackup(forceRestart: false)
                } else {
                    defaults.removeObject(forKey: activeIdKey)
                }
            } catch {
                // If we can’t read, don’t crash; just clear stale state
                defaults.removeObject(forKey: activeIdKey)
            }
        }


    }


    func disableBackup() async {
        self.uid = nil
    }

    /// Called on logout: stop any active uploads, end the session, clear identity, and publish idle.
    public func stopAndDisableBackup() async {
        // Gracefully end any active session (will cancel tasks & clear activeId)
        await endBackupSession()

        // Fully detach user identity
        self.uid = nil

        // Make sure UI observers see a stable idle state
        publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
    }


    /// User turned backup ON → create a new snapshot and make it active.
    func startNewBackupSession(name: String? = nil) async throws {
        cancelInitialBackupIfRunning()
        // If a session is already active (restored or just created), reuse it.
        if let active = self.activeBackupId {
            print("ℹ️ Reusing existing active backup \(active)")
            await self.syncActiveJournalSnapshotIfNeeded()
            publish(.init(state: .scanning, total: 0, done: 0, currentName: nil))
            startInitialBackup(forceRestart: true)
            return
        }

        guard let uid else { throw BackupError.missingUser }

        // Before creating a new one, see if there’s already an 'active' in Firestore (e.g., from another device)
        let col = db.collection("users").document(uid).collection("backups")
        if let existing = try? await col.whereField("status", isEqualTo: "active").limit(to: 1).getDocuments(),
           let existingId = existing.documents.first?.documentID {
            self.activeBackupId = existingId
            defaults.set(existingId, forKey: activeIdKey)
            // ⬇️ initialize metadata writer for incremental events
            let colRef = try self.clipsCollection(existingId)
            self.metadataWriter = FirestoreMetadataWriter(collection: colRef)
            await self.syncActiveJournalSnapshotIfNeeded()

            print("ℹ️ Found existing active backup in Firestore \(existingId); reusing")
            publish(.init(state: .scanning, total: 0, done: 0, currentName: nil))
            startInitialBackup(forceRestart: false)
            return
        }

        let backupId = UUID().uuidString

        let doc = try backupDoc(backupId)
        try await doc.setData([
            "createdAt": FieldValue.serverTimestamp(),
            "updatedAt": FieldValue.serverTimestamp(),
            "name": name ?? "Backup \(Date().formatted(date: .abbreviated, time: .shortened))",
            "status": "active",
            "deviceName": UIDevice.current.name
        ], merge: true)

        // Best-effort: close any other 'active' backups for this user so only this one remains active
        Task {
            do {
                let actives = try await col.whereField("status", isEqualTo: "active").getDocuments()
                for d in actives.documents where d.documentID != backupId {
                    try await col.document(d.documentID).setData([
                        "status": "completed",
                        "updatedAt": FieldValue.serverTimestamp()
                    ], merge: true)
                }
            } catch {
                print("⚠️ Could not complete stray active backups: \(error.localizedDescription)")
            }
        }

        self.activeBackupId = backupId
        defaults.set(backupId, forKey: activeIdKey)

        // ⬇️ initialize metadata writer for incremental events
        let colRef = try self.clipsCollection(backupId)
        self.metadataWriter = FirestoreMetadataWriter(collection: colRef)
        await self.syncActiveJournalSnapshotIfNeeded()

        publish(.init(state: .scanning, total: 0, done: 0, currentName: nil))
        // Kick off the full scan into this backup
        startInitialBackup(forceRestart: true)

    }

    /// User turned backup OFF → mark snapshot complete; stop incremental writes.
    func endBackupSession() async {

        isShuttingDown = true
        for t in uploadTasks { t.cancel() }
        uploadTasks.removeAll()
        cancelInitialBackupIfRunning()

        guard let backupId = activeBackupId else {
            isShuttingDown = false
            return
        }
        do {
            try await backupDoc(backupId).setData([
                "status": "completed",
                "updatedAt": FieldValue.serverTimestamp()
            ], merge: true)
        } catch {
            print("⚠️ Failed to mark backup completed: \(error)")
        }
        publish(.init(state: .finishing, total: 0, done: 0, currentName: nil))
        self.activeBackupId = nil
        defaults.removeObject(forKey: activeIdKey)

        // Flush and clear writer upon ending the session
        await metadataWriter?.flushNow()
        metadataWriter = nil

        publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
        isShuttingDown = false

    }


    // MARK: - Initial full backup
    func initialFullBackup() async {
        // --- Guards (don’t show “Scanning…” unless a session is active)
        guard let enumerator else { return }
        guard self.uid != nil else { return }
        guard let backupId = self.activeBackupId else {
            print("ℹ️ No active backup; skipping initialFullBackup.")
            publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
            return
        }

        // Ensure a writer is ready even if we didn’t come through startNewBackupSession()
        if self.metadataWriter == nil {
            do {
                let colRef = try self.clipsCollection(backupId)
                self.metadataWriter = FirestoreMetadataWriter(collection: colRef)
            } catch {
                print("⚠️ Unable to initialize metadata writer: \(error.localizedDescription)")
            }
        }


        // Safe to tell UI we're scanning now
        publish(.init(state: .scanning, total: 0, done: 0, currentName: nil))

        // (optional) trace one run
        let runTag = UUID().uuidString.prefix(6)
        print("▶️ initialFullBackup start [\(runTag)]")
        defer { print("⏹️ initialFullBackup end   [\(runTag)]") }

        // … after enumeration …
        if Task.isCancelled || isShuttingDown || self.activeBackupId != backupId {
            print("ℹ️ initialFullBackup aborted before hashing")
            publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
            return
        }

        // … after hashing / preflight …
        if Task.isCancelled || isShuttingDown || self.activeBackupId != backupId {
            print("ℹ️ initialFullBackup aborted before uploads")
            publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
            return
        }


        // --- 1) Enumerate, but read ONLY size now (no hashing yet)
        let base = await MainActor.run { enumerator() }

        // A light record to avoid hashing early
        struct Lite {
            let id: String
            let url: URL
            let bytes: Int64
            let createdAt: Date
            let journalId: String?
            let ext: String
        }

        var lite: [Lite] = []
        lite.reserveCapacity(base.count)

        for item in base {
            do {
                let attrs = try FileManager.default.attributesOfItem(atPath: item.fileURL.path)
                let bytes = (attrs[.size] as? NSNumber)?.int64Value ?? 0
                lite.append(.init(id: item.id,
                                  url: item.fileURL,
                                  bytes: bytes,
                                  createdAt: item.createdAt,
                                  journalId: item.journalId,
                                  ext: item.ext))
            } catch {
                print("⚠️ Skipping \(item.fileURL.lastPathComponent): \(error)")
            }
        }



        // --- 2) Pre-flight (batched Firestore): decide what needs work
        var toHashOrUpload: [Lite] = []
        do {
            let coll = try self.clipsCollection(backupId)
            let snapshot = try await coll.getDocuments()   // single roundtrip
            var remote: [String: (sha: String, bytes: Int64, deleted: Bool)] = [:]
            for d in snapshot.documents {
                let data = d.data()
                let sha = data["sha256"] as? String ?? ""
                let bytes = Self.int64Value(data["bytes"]) ?? -1
                let deleted = (data["deleted"] as? Bool) ?? false
                remote[d.documentID] = (sha, bytes, deleted)
            }

            for l in lite {
                if let r = remote[l.id], r.deleted == false {
                    // if bytes differ, we definitely need to upload; don't hash yet
                    if r.bytes != l.bytes {
                        toHashOrUpload.append(l)
                        continue
                    }
                    // bytes equal → we must hash THIS ONE to confirm
                    toHashOrUpload.append(l)
                } else {
                    // no remote doc → needs upload
                    toHashOrUpload.append(l)
                }
            }
        } catch {
            print("❌ initialFullBackup: preflight snapshot failed: \(error.localizedDescription)")
            // If preflight fails (offline), assume all need upload
            toHashOrUpload = lite
        }

        // we will hash only these candidates
        let prepareTotal = toHashOrUpload.count
        publish(.init(state: .preparing, total: prepareTotal, done: 0, currentName: nil))
        var prepareDone = 0


        // --- 3) Hash only the clips that might change / need upload (parallel, capped)
        nonisolated func makeLocalClip(from l: Lite) async throws -> LocalClip {
            try await self.prepareLocalClip(id: l.id,
                                            url: l.url,
                                            createdAt: l.createdAt,
                                            journalId: l.journalId,
                                            ext: l.ext)
        }

        var prepared: [LocalClip] = []
        prepared.reserveCapacity(toHashOrUpload.count)

        if toHashOrUpload.isEmpty {
            // nothing to hash or upload
            publish(.init(state: .finishing, total: 0, done: 0, currentName: nil))
            publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
            print("✅ Initial backup: library already up to date.")
            return
        }

        let hashGate = Gate(maxParallelHashes)
        await withTaskGroup(of: LocalClip?.self) { group in
            for l in toHashOrUpload {
                group.addTask {
                    await hashGate.acquire()
                    defer { Task { await hashGate.release() } }
                    do {
                        let clip = try await makeLocalClip(from: l)
                        // progress for hashing
                        await MainActor.run {
                            prepareDone += 1
                            self.publish(.init(state: .preparing,
                                               total: prepareTotal,
                                               done: prepareDone,
                                               currentName: l.id))
                        }
                        return clip
                    } catch {
                        print("⚠️ Hashing failed for \(l.id): \(error.localizedDescription)")
                        await MainActor.run {
                            prepareDone += 1
                            self.publish(.init(state: .preparing,
                                               total: prepareTotal,
                                               done: prepareDone,
                                               currentName: l.id))
                        }
                        return nil
                    }
                }
            }
            for await maybe in group {
                if let clip = maybe { prepared.append(clip) }
            }
        }


        // If preflight snapshot was available, skip ones that are actually up-to-date
        var toUpload: [LocalClip] = []
        do {
            let coll = try self.clipsCollection(backupId)
            let snapshot = try await coll.getDocuments()
            var remote: [String: (sha: String, bytes: Int64, deleted: Bool)] = [:]
            for d in snapshot.documents {
                let data = d.data()
                let sha = data["sha256"] as? String ?? ""
                let bytes = Self.int64Value(data["bytes"]) ?? -1
                let deleted = (data["deleted"] as? Bool) ?? false
                remote[d.documentID] = (sha, bytes, deleted)
            }
            for clip in prepared {
                if let r = remote[clip.id],
                   r.deleted == false,
                   r.sha == clip.sha256,
                   r.bytes == clip.bytes {
                    continue // already up to date
                }
                toUpload.append(clip)
            }
        } catch {
            // If snapshot read fails now, upload all prepared
            toUpload = prepared
        }

        // --- 4) Upload loop (parallel, capped)
        let totalWork = toUpload.count
        print("ℹ️ Initial backup: toUpload=\(totalWork) / prepared=\(prepared.count)")

        guard totalWork > 0 else {
            print("✅ Initial backup: nothing to upload after preflight.")
            publish(.init(state: .finishing, total: 0, done: 0, currentName: nil))
            publish(.init(state: .idle, total: 0, done: 0, currentName: nil))
            return
        }

        // now announce uploading
        publish(.init(state: .uploading, total: totalWork, done: 0, currentName: nil))


        let gate = Gate(maxParallelUploads)
        var done = 0
        var succeeded = 0

        await withTaskGroup(of: Void.self) { group in
            for clip in toUpload {
                group.addTask {
                    await gate.acquire()
                    defer { Task { await gate.release() } }

                    let shouldStop = await MainActor.run { self.isShuttingDown || self.activeBackupId != backupId }
                    if shouldStop || Task.isCancelled { return }

                    print("⬆️  Upload starting: \(clip.id).\(clip.ext) (\(clip.bytes) bytes)")

                    do {
                        try await self.uploadIfNeeded(clip)
                        print("✅ Upload finished: \(clip.id).\(clip.ext)")
                        await MainActor.run { succeeded += 1 }
                    } catch {
                        print("❌ Upload failed for \(clip.id): \(error.localizedDescription)")
                    }

                    await MainActor.run {
                        done += 1
                        self.publish(.init(state: .uploading, total: totalWork, done: done, currentName: clip.id))
                    }
                }
            }
            await group.waitForAll()
        }

         if isShuttingDown || self.activeBackupId != backupId || Task.isCancelled {
             publish(.init(state: .idle, total: succeeded, done: succeeded, currentName: nil))
             print("ℹ️ Initial backup aborted: uploaded \(succeeded) before stop.")
             return
         }

        // Flush any queued metadata writes before finishing
        await metadataWriter?.flushNow()
        if succeeded > 0 {
            await touchBackup(backupId)
        }
        publish(.init(state: .finishing, total: succeeded, done: succeeded, currentName: nil))
        publish(.init(state: .idle, total: succeeded, done: succeeded, currentName: nil))
        print("✅ Initial backup complete. Uploaded \(succeeded) / \(totalWork).")
    }


    // MARK: - Upload + metadata
    private func uploadIfNeeded(_ clip: LocalClip) async throws {
        guard !isShuttingDown, let backupId = self.activeBackupId else {
            throw BackupError.storageUploadFailed   // or .aborted if you add it
        }
        let coll = try self.clipsCollection(backupId)
        let docRef = coll.document(clip.id)

        // Check existing metadata
        let existing = try await docRef.getDocument()
        if let data = existing.data(),
           let remoteSha = data["sha256"] as? String,
           let remoteBytes = Self.int64Value(data["bytes"]),
           remoteSha == clip.sha256,
           remoteBytes == clip.bytes,
           (data["deleted"] as? Bool) != true {
            // Already up-to-date
            return
        }

        // Upload to Storage
        let bucket = try self.clipsBucket(backupId)
        let objectRef = bucket.child("\(clip.id).\(clip.ext)")
        let metadata = StorageMetadata()
        metadata.contentType = mimeType(for: clip.ext)

        try await putFile(from: clip.fileURL, to: objectRef, metadata: metadata)

        // Write Firestore metadata (upsert)
        let doc: [String: Any] = [
            "path": objectRef.fullPath,
            "bytes": clip.bytes,
            "sha256": clip.sha256,
            "createdAt": Timestamp(date: clip.createdAt),
            "journalId": clip.journalId as Any,
            "ext": clip.ext,
            "deleted": false
        ]
        await metadataWriter?.enqueue(id: clip.id, doc: doc)
    }

    private func putFile(from url: URL,
                         to ref: StorageReference,
                         metadata: StorageMetadata?) async throws {
        // If the file doesn’t exist locally, bail
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw BackupError.missingFile
        }

        return try await withCheckedThrowingContinuation { cont in
            var task: StorageUploadTask? = nil

            task = ref.putFile(from: url, metadata: metadata) { _, error in
                // remove from tracking
                if let t = task {
                    self.uploadTasks.removeAll { $0 === t }
                }

                if let error {
                    cont.resume(throwing: error)
                } else {
                    cont.resume(returning: ())
                }
            }

            // keep a handle so we can cancel on sign-out / toggle OFF
            if let t = task {
                self.uploadTasks.append(t)

                // Optional: progress logging
                t.observe(.progress) { snap in
                    guard let p = snap.progress else { return }
                    guard p.totalUnitCount > 0 else { return }
                    let ratio = Double(p.completedUnitCount) / Double(p.totalUnitCount)
                    // Guard against NaN/Infinity which crashes Int() conversion
                    guard ratio.isFinite else { return }
                    let pct = Int(ratio * 100)
                    print("Upload \(ref.name): \(pct)% (\(p.completedUnitCount)/\(p.totalUnitCount) bytes)")
                }

                // Only log failures here; do not resume the continuation again
                t.observe(.failure) { snap in
                    if let e = snap.error {
                        print("❌ Storage failure \(ref.fullPath): \(e.localizedDescription)")
                    }
                }
            }
        }
    }


    private nonisolated func prepareLocalClip(id: String, url: URL, createdAt: Date, journalId: String?, ext: String) async throws -> LocalClip {
        let attrs = try FileManager.default.attributesOfItem(atPath: url.path)
        let bytes = (attrs[.size] as? NSNumber)?.int64Value ?? 0
        let mtime = (attrs[.modificationDate] as? Date)?.timeIntervalSince1970 ?? 0
        let key = HashKey(path: url.path, size: bytes, mtime: mtime)

        let hash: String
        if let cached = await hashCache.value(for: key) {
            hash = cached
        } else {
            let h = try sha256(forFileAt: url)
            await hashCache.store(h, for: key)
            hash = h
        }

        return LocalClip(id: id,
                         fileURL: url,
                         bytes: bytes,
                         sha256: hash,
                         createdAt: createdAt,
                         journalId: journalId,
                         ext: ext)
    }


    /// Call when a brand-new local clip is saved.
    func onLocalClipAdded(id: String, fileURL: URL, createdAt: Date, journalId: String?, ext: String) {
        Task {
            guard uid != nil else { return }
            guard self.activeBackupId != nil else { return } // backup is OFF → no-op
            do {
                try await worker.run {
                    // BEFORE you prepare/upload:
                    self.publish(.init(state: .uploading, total: 1, done: 0, currentName: id))

                    let clip = try await self.prepareLocalClip(id: id, url: fileURL, createdAt: createdAt, journalId: journalId, ext: ext)
                    try await self.uploadIfNeeded(clip)
                    if let backupId = self.activeBackupId {
                        await self.touchBackup(backupId)
                    }

                    // AFTER success:
                    self.publish(.init(state: .finishing, total: 1, done: 1, currentName: id))
                    self.publish(.init(state: .idle, total: 1, done: 1, currentName: nil))
                }
            } catch {
                // (keep your existing print)
                self.publish(.init(state: .error, total: 1, done: 0, currentName: id))
            }

        }
    }


    /// Call when a local clip is deleted (immediate blob delete + tombstone doc).
    /// Call when a local clip is deleted (immediate blob delete + tombstone doc) for the ACTIVE backup.
    func onLocalClipDeleted(id: String, ext: String?) {
        Task {
            guard uid != nil else { return }
            guard let backupId = self.activeBackupId else { return } // backup is OFF → no-op
            do {
                try await worker.run {
                    // 1) Read doc to get authoritative storage path (best-effort)
                    let coll   = try self.clipsCollection(backupId)
                    let docRef = coll.document(id)

                    var storageRefToDelete: StorageReference? = nil
                    do {
                        let snap = try await docRef.getDocument()
                        if let data = snap.data(), let path = data["path"] as? String, !path.isEmpty {
                            storageRefToDelete = self.storage.reference(withPath: path)
                        }
                    } catch {
                        // Firestore read can fail (offline); we'll fall back below.
                        print("ℹ️ onLocalClipDeleted: could not read doc for \(id): \(error.localizedDescription)")
                    }

                    // 2) Fallbacks if no path on the doc → use the backup-scoped bucket
                    if storageRefToDelete == nil {
                        let bucket = try self.clipsBucket(backupId)
                        if let ext {
                            storageRefToDelete = bucket.child("\(id).\(ext)")
                        } else {
                            // Final safety: try common extensions until one deletes
                            let candidates = ["mov","mp4","m4v","jpg","jpeg","png","heic"]
                            for e in candidates {
                                let ref = bucket.child("\(id).\(e)")
                                do { try await ref.delete(); storageRefToDelete = ref; break } catch { /* keep trying */ }
                            }
                        }
                    }

                    // 3) Delete the storage object (if we resolved any path)
                    if let objectRef = storageRefToDelete {
                        do { try await objectRef.delete() }
                        catch { print("⚠️ Storage delete failed for \(id): \(error.localizedDescription)") }
                    } else {
                        print("⚠️ No storage path resolved for \(id); blob may already be gone.")
                    }

                    // 4) Tombstone the Firestore doc (and record deletedAt)
                    try await docRef.setData([
                        "deleted": true,
                        "deletedAt": FieldValue.serverTimestamp()
                    ], merge: true)
                    await self.touchBackup(backupId)
                }
            } catch {
                print("❌ Incremental delete failed for \(id): \(error)")
            }
        }
    }
}


enum BackupError: Error {
    case missingUser
    case missingFile
    case unsupportedType
    case firestoreWriteFailed
    case storageUploadFailed
}

private func mimeType(for ext: String) -> String {
    switch ext.lowercased() {
    case "mp4", "m4v": return "video/mp4"
    case "mov":        return "video/quicktime"
    case "jpg", "jpeg":return "image/jpeg"
    case "png":        return "image/png"
    case "heic":       return "image/heic"
    default:           return "application/octet-stream"
    }
}

// MARK: - SHA256
private func sha256(forFileAt url: URL) throws -> String {
    let handle = try FileHandle(forReadingFrom: url)
    defer { try? handle.close() }

    var hasher = SHA256()
    while autoreleasepool(invoking: {
        let data = try? handle.read(upToCount: 1_048_576) // 1 MB chunks
        if let data, !data.isEmpty {
            hasher.update(data: data)
            return true
        }
        return false
    }) {}
    let digest = hasher.finalize()
    return digest.map { String(format: "%02x", $0) }.joined()
}


// MARK: - Types (keep small & transport-friendly)

struct LocalClip {
    let id: String           // stable local id
    let fileURL: URL         // local path to media
    let bytes: Int64
    let sha256: String       // we’ll compute in Step 2
    let createdAt: Date
    let journalId: String?   // project/journal foreign key
    let ext: String          // "mov", "mp4", "jpg", etc.
}

struct RemoteClip: Codable {
    let path: String         // storage path "users/{uid}/clips/{clipId}.ext"
    let bytes: Int64
    let sha256: String
    let createdAt: Date
    let journalId: String?
    let ext: String
    let deleted: Bool        // tombstone
}
